_wandb:
    value:
        cli_version: 0.21.3
        e:
            wm7vznqodx75uu6dlauntdrsp5a9en7f:
                args:
                    - --depth=20
                    - --max_seq_len=2048
                    - --device_batch_size=16
                    - --total_batch_size=524288
                    - --resume_from_step=1000
                    - --eval_every=250
                    - --save_every=1000
                    - --core_metric_every=2000
                    - --sample_every=2000
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "41922297856"
                        used: "20007747584"
                email: c.okocha@ufl.edu
                executable: /orange/ufdatastudios/c.okocha/chibu-chat/.venv/bin/python
                git:
                    commit: eacd361380837b3e2367b2fd767b2d8e44ee0059
                    remote: https://github.com/unruli/chibu-chat.git
                gpu: NVIDIA B200
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-497788a5-8172-674b-6665-11631ed2893f
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-56454440-ca53-fcc2-275a-aafc6a142e77
                host: c1001a-s25.ufhpc
                memory:
                    total: "2163693289472"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: -m scripts.base_train
                python: CPython 3.10.18
                root: /orange/ufdatastudios/c.okocha/chibu-chat
                slurm:
                    cluster_name: hipergator
                    conf: /opt/slurm/etc/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus: "2"
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: ufdatastudios
                    job_cpus_per_node: "16"
                    job_end_time: "1770522660"
                    job_gid: "4329"
                    job_gpus: 1,2
                    job_id: "24547785"
                    job_name: nanochat-resume-compile
                    job_nodelist: c1001a-s25
                    job_num_nodes: "1"
                    job_partition: hpg-b200
                    job_qos: ufdatastudios
                    job_start_time: "1770436260"
                    job_uid: "2114"
                    job_user: c.okocha
                    jobid: "24547785"
                    localid: "0"
                    mem_per_node: "131072"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: c1001a-s25
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /orange/ufdatastudios/c.okocha/chibu-chat
                    submit_host: login10.ufhpc
                    task_pid: "370213"
                    tasks_per_node: "1"
                    tmpdir: /scratch/local/24547785
                    topology_addr: ibswb200.ibsw0902.c1001a-s25
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=16
                startedAt: "2026-02-07T03:55:52.449490Z"
                writerId: wm7vznqodx75uu6dlauntdrsp5a9en7f
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
core_metric_every:
    value: 2000
core_metric_max_per_task:
    value: 500
depth:
    value: 20
device_batch_size:
    value: 16
device_type:
    value: ""
embedding_lr:
    value: 0.2
eval_every:
    value: 250
eval_tokens:
    value: 10485760
final_lr_frac:
    value: 0
grad_clip:
    value: 1
matrix_lr:
    value: 0.02
max_seq_len:
    value: 2048
model_tag:
    value: ""
num_iterations:
    value: -1
resume_from_step:
    value: 1000
run:
    value: resume_compile_24547785_20260206_2251
sample_every:
    value: 2000
save_every:
    value: 1000
target_flops:
    value: -1
target_param_data_ratio:
    value: 20
total_batch_size:
    value: 524288
unembedding_lr:
    value: 0.004
warmdown_ratio:
    value: 0.2
warmup_ratio:
    value: 0
weight_decay:
    value: 0
