_wandb:
    value:
        cli_version: 0.21.3
        e:
            92e3q9rbob13lzam95qiutce8fps0jb1:
                args:
                    - --max_chars=2000000000
                    - --vocab_size=65536
                    - --doc_cap=10000
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "41922297856"
                        used: "19787689984"
                email: c.okocha@ufl.edu
                executable: /orange/ufdatastudios/c.okocha/chibu-chat/.venv/bin/python
                git:
                    commit: eacd361380837b3e2367b2fd767b2d8e44ee0059
                    remote: https://github.com/unruli/chibu-chat.git
                gpu: NVIDIA B200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-1d68f287-cdce-cf2a-27df-c713ee913bfe
                host: c0906a-s25.ufhpc
                memory:
                    total: "2163693277184"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: -m scripts.tok_train
                python: CPython 3.10.18
                root: /orange/ufdatastudios/c.okocha/chibu-chat
                slurm:
                    cluster_name: hipergator
                    conf: /opt/slurm/etc/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000000007F0000001
                    cpu_bind_list: "0x00000000000000000007F0000001"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: block
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: ufdatastudios
                    job_cpus_per_node: "8"
                    job_end_time: "1769556202"
                    job_gid: "4329"
                    job_gpus: "0"
                    job_id: "23901247"
                    job_name: nanochat-tokenizer
                    job_nodelist: c0906a-s25
                    job_num_nodes: "1"
                    job_partition: hpg-b200
                    job_qos: ufdatastudios
                    job_start_time: "1769538202"
                    job_uid: "2114"
                    job_user: c.okocha
                    jobid: "23901247"
                    launch_node_ipaddr: 172.16.139.189
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: c0906a-s25
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    srun_comm_host: 172.16.139.189
                    srun_comm_port: "46285"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "46285"
                    step_nodelist: c0906a-s25
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /orange/ufdatastudios/c.okocha/chibu-chat
                    submit_host: login9.ufhpc
                    task_pid: "1647861"
                    tasks_per_node: "1"
                    tmpdir: /scratch/local/23901247
                    topology_addr: ibswb200.ibsw0908.c0906a-s25
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=8
                    umask: "0022"
                startedAt: "2026-01-27T18:27:26.094535Z"
                writerId: 92e3q9rbob13lzam95qiutce8fps0jb1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
doc_cap:
    value: 10000
max_chars:
    value: 2000000000
task:
    value: tokenizer_training
vocab_size:
    value: 65536
